name: Build Release Images
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Tag to build for
  push:
    tags:
      - '*'

jobs:
  prepare:
    name: Select the tag to build for and create Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Set tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" != "push" ]]; then
            tag="${{ github.event.inputs.tag }}"
          else
            tag=$(basename "${{ github.ref }}")
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Create GitHub Draft Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          tag="${{ steps.tag.outputs.tag }}"
          body="Pre-release for @${{ steps.tag.outputs.tag }}"
          gh release create --draft "$tag" --title "$tag-pre" --notes "$body"

  build_fox:
    needs: [prepare]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.tag }}
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2.2
          target: esp32s3
          command: ./rg_tool.py --target fri3d-2024 build launcher retro-core prboom-go
      - name: Upload binaries to draft release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          sudo chown -R $(whoami) {launcher,retro-core,prboom-go}/build
          mv launcher/build/launcher.bin retro_go_launcher_fox.bin
          mv retro-core/build/retro-core.bin retro_go_core_fox.bin
          mv prboom-go/build/prboom-go.bin retro_go_prboom_fox.bin
          gh release upload "${{ needs.prepare.outputs.tag }}" \
            "retro_go_launcher_fox.bin" \
            "retro_go_core_fox.bin" \
            "retro_go_prboom_fox.bin"
